<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Build Your Own_view360_list</name>
   <tag></tag>
   <elementGuidId>e3576755-810d-4057-a911-a800e8d28d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.view360__colors-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='view360__colors-list']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.view360__colors-wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e326dc90-91c4-414e-b5b0-23692ec48f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view360__colors-wrapper</value>
      <webElementGuid>344c7e48-bd85-4783-976c-78f28e948674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config-360-view&quot;)/div[@class=&quot;view360__container&quot;]/div[@class=&quot;view360__bottom-section&quot;]/div[@class=&quot;view360__colors-wrapper&quot;]</value>
      <webElementGuid>7bcd98b4-ecde-42eb-9a23-c44f8e3a6fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='config-360-view']/div/div[2]/div</value>
      <webElementGuid>f9a2d8f8-b3dd-41ff-a8cf-dc9282751573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Your Own'])[2]/following::div[2]</value>
      <webElementGuid>14cd6ce8-2220-477e-be59-478512847af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagine It. Customise It.'])[1]/following::div[5]</value>
      <webElementGuid>b16d5a0c-1f4e-4dc2-9c20-6b6449603fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exterior'])[1]/preceding::div[24]</value>
      <webElementGuid>4d90383e-cc9f-405b-84e7-2702744450e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interior'])[1]/preceding::div[24]</value>
      <webElementGuid>d34a01ee-bdb6-4194-972a-21e62ba2297d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div</value>
      <webElementGuid>84e42e72-3fd0-4a21-8344-1e1b4b5acc8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
