<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Build Your Own_view360_list - click</name>
   <tag></tag>
   <elementGuidId>fe06a7e7-0c5d-4806-9521-0856baa82221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.view360__colors-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='view360__colors-list']/div)[${i}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.view360__colors-wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>373ded2f-f4ba-44dd-abec-235f35d943f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view360__colors-wrapper</value>
      <webElementGuid>02e5ccbc-a6d8-4e93-87ad-5ccfa8f4eb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config-360-view&quot;)/div[@class=&quot;view360__container&quot;]/div[@class=&quot;view360__bottom-section&quot;]/div[@class=&quot;view360__colors-wrapper&quot;]</value>
      <webElementGuid>2de9965b-684e-4166-a0ea-0e5d06c42a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='config-360-view']/div/div[2]/div</value>
      <webElementGuid>40d36ee1-1b06-4e61-aaa3-4222afa724bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Your Own'])[2]/following::div[2]</value>
      <webElementGuid>1023af84-6c22-438d-9848-53131f3da7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagine It. Customise It.'])[1]/following::div[5]</value>
      <webElementGuid>983352de-24db-406c-9c7d-25b636df6eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exterior'])[1]/preceding::div[24]</value>
      <webElementGuid>5d3f2e3d-2f0c-47aa-b3f0-6a9d0e88032c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interior'])[1]/preceding::div[24]</value>
      <webElementGuid>3aeae216-bc5b-4717-bf76-07478c9645ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/div</value>
      <webElementGuid>b5110834-258c-49cc-8b4e-ebcb8349ec3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
