<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Beyond Imagination</name>
   <tag></tag>
   <elementGuidId>c2d18472-b3f0-41e9-b78a-2ca5f67345ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beyond-imagination</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='beyond-imagination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Beyond Imagination&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fc2e1214-a860-42df-a54a-cfd5a6a03a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beyond-imagination</value>
      <webElementGuid>efb5197e-0295-4540-866a-866847f60c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yy8-highlight-tabs__title</value>
      <webElementGuid>e3b48258-69e3-4536-93d7-7c75a2d86740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beyond Imagination</value>
      <webElementGuid>8aa87628-2342-41f7-bc0e-71c5bcf8fffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beyond-imagination&quot;)</value>
      <webElementGuid>683eab19-2fc9-4855-b3f9-e130cc675b74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='beyond-imagination']</value>
      <webElementGuid>198e8abf-7a60-444e-bea3-2f43ecbe7630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safety-block']/div/div/h2</value>
      <webElementGuid>e938614e-a5d7-49d9-9076-8757819e368a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety'])[2]/following::h2[1]</value>
      <webElementGuid>51afe71b-fbfe-4928-8c60-be61c96725f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driving Performance'])[2]/following::h2[1]</value>
      <webElementGuid>824b919b-594b-45f7-a6fc-feeab170339f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High Capacity Battery'])[1]/preceding::h2[1]</value>
      <webElementGuid>be3d5188-c56c-4a1e-8780-30c2ce051384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADAS Level 2'])[1]/preceding::h2[1]</value>
      <webElementGuid>4b98a3a6-d640-483b-9ace-5c63238e7fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beyond Imagination']/parent::*</value>
      <webElementGuid>cdfeb4db-2c0f-4d43-9d9f-0b152b0fb405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h2</value>
      <webElementGuid>b3a2b46e-60f7-4df8-ba64-25d309f3e669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'beyond-imagination' and (text() = 'Beyond Imagination' or . = 'Beyond Imagination')]</value>
      <webElementGuid>630dd4d6-3965-4030-af3e-9239ecf34c1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
