<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Comfort Like Never Before</name>
   <tag></tag>
   <elementGuidId>557876c0-6055-4639-a9a1-70202bc5c44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comfort-like-never-before</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='comfort-like-never-before']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Comfort Like Never Before&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6bdac225-221f-427a-865c-1f41761b3dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comfort-like-never-before</value>
      <webElementGuid>a3cf02af-d554-445b-b6fd-4a2f6105e56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yy8-highlight-tabs__title</value>
      <webElementGuid>b4957b73-9d76-4a89-93e7-207557e2cf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comfort Like Never Before</value>
      <webElementGuid>9f45b353-2181-4b5f-8af3-43f76ffca51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comfort-like-never-before&quot;)</value>
      <webElementGuid>a2a59a9d-1f2e-4c5d-b87d-c5f01b90d5f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='comfort-like-never-before']</value>
      <webElementGuid>154424da-219b-4e18-9965-0a6704ef7ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comfort-block']/div/div/h2</value>
      <webElementGuid>b6769d6b-50d9-4b16-b6fb-bd734d9648b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagine'])[1]/following::h2[1]</value>
      <webElementGuid>bf96ee36-de35-4820-9555-8040af68e1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wireless Charger'])[1]/following::h2[1]</value>
      <webElementGuid>e2fdb317-b1da-4418-8f31-9fe7bb01d4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Wheelbase'])[1]/preceding::h2[1]</value>
      <webElementGuid>d87a81cc-14e5-45e2-b34a-b80afa2d25d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventilated Seats'])[1]/preceding::h2[1]</value>
      <webElementGuid>6fd01bf3-8674-454e-8bb0-8f2b9ae8af0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comfort Like Never Before']/parent::*</value>
      <webElementGuid>9d3a43fd-c229-44f2-bf7a-43cbce6406ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h2</value>
      <webElementGuid>a31bb12a-c615-4462-bfff-1186f986db20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'comfort-like-never-before' and (text() = 'Comfort Like Never Before' or . = 'Comfort Like Never Before')]</value>
      <webElementGuid>91b92690-34f7-400a-8b1e-b702fe16528b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
