<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_e for me</name>
   <tag></tag>
   <elementGuidId>acf78303-b952-40bd-b7a0-c1e9693ea1cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#like-a-beast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='e-for-me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Like A Beast&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1f23b7a1-2f2d-446a-96f9-9f34d1091164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>like-a-beast</value>
      <webElementGuid>5c59a420-9e3e-4767-b494-00de5fd34ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yy8-highlight-tabs__title</value>
      <webElementGuid>f2e62780-4584-4011-93af-90bc3678bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Like A Beast</value>
      <webElementGuid>b3c64c2f-64bf-44ba-ba3e-09b710a843bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;like-a-beast&quot;)</value>
      <webElementGuid>2f85bcb9-611d-4b93-9188-140516f4406e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='like-a-beast']</value>
      <webElementGuid>4377d434-2782-44d7-a248-983fad3f6cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='performance-block']/div/div/h2</value>
      <webElementGuid>7dd15bec-57d3-49e5-b5aa-48974935a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performs'])[1]/following::h2[1]</value>
      <webElementGuid>ecc40e37-29bd-4991-a884-10946d9e24f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexible Boot Space'])[2]/following::h2[1]</value>
      <webElementGuid>d12ce0a1-0987-48d5-ab62-48ac46b7d7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pure Electric Platform'])[1]/preceding::h2[1]</value>
      <webElementGuid>d8ffe619-a352-406d-9ef2-f2bc350b40bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Aerodynamics'])[1]/preceding::h2[1]</value>
      <webElementGuid>f31c6974-cdfd-4fca-949a-3cc5ae5e1b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Like A Beast']/parent::*</value>
      <webElementGuid>b4f101bb-c90f-499f-97f1-fc09bf23536b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/h2</value>
      <webElementGuid>c39add94-7791-41ee-bf66-e198ad2458f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'like-a-beast' and (text() = 'Like A Beast' or . = 'Like A Beast')]</value>
      <webElementGuid>742fb4b4-65c4-410d-bd7b-e6f96854861e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
