<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Futuristic  Spacious Cabin</name>
   <tag></tag>
   <elementGuidId>61a0e6df-b0ec-4ec7-b03e-2b454ce5677c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#futuristic--spacious-cabin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='futuristic--spacious-cabin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Futuristic &amp; Spacious Cabin&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>447b5cf6-60a8-4dcc-8755-9ee6f84f4907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>futuristic--spacious-cabin</value>
      <webElementGuid>c5827d58-b9c8-40e2-826e-81111819bdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-text</value>
      <webElementGuid>9b369b4e-0123-4bae-b716-a1fbda97ce0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Futuristic &amp; Spacious Cabin</value>
      <webElementGuid>1ac793a0-5484-4f99-adb2-266540a2ff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;futuristic--spacious-cabin&quot;)</value>
      <webElementGuid>db8c7fcb-03f0-4363-aead-3e964a7c751b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='futuristic--spacious-cabin']</value>
      <webElementGuid>f1988163-dcae-42eb-a2fc-9fb6c4aaa1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='interior-block']/div/div[2]/div/h2</value>
      <webElementGuid>7e2bd129-0723-472c-a7b1-b91a6ecc3775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Modal Dialog'])[3]/following::h2[1]</value>
      <webElementGuid>387b8979-2fb9-4917-808d-2d3cd2d27597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[3]/following::h2[1]</value>
      <webElementGuid>1cdd1007-2aad-4d6d-94da-1717ec660b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambient Lighting With Multi Colour Illumination'])[1]/preceding::h2[1]</value>
      <webElementGuid>1817ac0d-9832-428b-872a-28552bc574cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twindeck Floating Console With Shift By Wire'])[1]/preceding::h2[1]</value>
      <webElementGuid>bbae5294-f60d-44e8-a2ff-28184178e3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Futuristic &amp; Spacious Cabin']/parent::*</value>
      <webElementGuid>1c9a7dc4-9e58-47d1-9320-049563b7044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/h2</value>
      <webElementGuid>bfac3484-ee2a-46d9-9dd2-41e5fa6fac49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'futuristic--spacious-cabin' and (text() = 'Futuristic &amp; Spacious Cabin' or . = 'Futuristic &amp; Spacious Cabin')]</value>
      <webElementGuid>8d0b5a44-ea15-4252-9451-d0747007d51e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
