<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Imagine It. Customise It</name>
   <tag></tag>
   <elementGuidId>5a0660c6-8d69-41f9-802f-691a29d0c940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imagine-it-customise-it</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='imagine-it-customise-it']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Imagine It. Customise It.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>0ccebba5-379f-46cc-afe6-8b1e545cd6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imagine-it-customise-it</value>
      <webElementGuid>9166874d-81ee-4cca-b9a7-14582fe65c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view360__title</value>
      <webElementGuid>4c4a7487-34b3-4070-ade2-cb442314a359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imagine It. Customise It.</value>
      <webElementGuid>29303d08-8b13-4542-b707-79c72dfe365e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imagine-it-customise-it&quot;)</value>
      <webElementGuid>22eae706-95f0-4236-a6d3-319ee0326cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='imagine-it-customise-it']</value>
      <webElementGuid>ad4b89d9-f277-4a0f-95dd-2692a4e5b26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='config-360-view']/div/div/div/h2</value>
      <webElementGuid>eb01a71b-0f82-45cc-80f4-772462f540f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Charging'])[2]/following::h2[1]</value>
      <webElementGuid>9860e122-aeb0-44dd-8cc9-60d9845b02de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suzuki Navigation'])[2]/following::h2[1]</value>
      <webElementGuid>02c37269-e827-4674-803f-bb2074646c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build Your Own'])[2]/preceding::h2[1]</value>
      <webElementGuid>81fa6970-3503-4e6d-84ee-debf705d9552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exterior'])[1]/preceding::h2[1]</value>
      <webElementGuid>d2f844e8-4a82-404f-bf62-b1ca02a81979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imagine It. Customise It.']/parent::*</value>
      <webElementGuid>c23508ad-ebd6-4db9-a690-c23ba4eba541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/h2</value>
      <webElementGuid>b62e546e-ae35-467b-a86d-47ce39577b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'imagine-it-customise-it' and (text() = 'Imagine It. Customise It.' or . = 'Imagine It. Customise It.')]</value>
      <webElementGuid>79361fd0-81bc-43a6-886b-a7889e967dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
