<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Like A Beast</name>
   <tag></tag>
   <elementGuidId>aa84b771-634d-4f0e-a3b5-3ac0f26d3303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#like-a-beast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='like-a-beast']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Like A Beast&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>bc150f19-b033-4a30-b222-50ceb97880dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>like-a-beast</value>
      <webElementGuid>bace3803-8e61-4e42-9a46-417a74df17b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yy8-highlight-tabs__title</value>
      <webElementGuid>001f5c09-5ea0-4615-bd11-d77cbc4db1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Like A Beast</value>
      <webElementGuid>36d64c05-9a3c-420d-acd1-a9058a9b4e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;like-a-beast&quot;)</value>
      <webElementGuid>6c900df4-75f0-4e97-b00e-6426572470ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='like-a-beast']</value>
      <webElementGuid>5e400bec-daa4-472c-a429-be85529c2398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='performance-block']/div/div/h2</value>
      <webElementGuid>c6119676-7b9e-4442-bbad-20de538b3ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performs'])[1]/following::h2[1]</value>
      <webElementGuid>4b7f1082-d6da-41c4-8654-a8da30eecff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexible Boot Space'])[2]/following::h2[1]</value>
      <webElementGuid>cdcbce7b-e8e7-4a52-8722-19dc2e650225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pure Electric Platform'])[1]/preceding::h2[1]</value>
      <webElementGuid>38590d10-8989-44fc-909c-98ae62db79a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Aerodynamics'])[1]/preceding::h2[1]</value>
      <webElementGuid>181688ed-f9fe-4c13-bf57-12e8dbb4f429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Like A Beast']/parent::*</value>
      <webElementGuid>b07f36a6-ac87-4c94-a94d-2ec236623ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/h2</value>
      <webElementGuid>d9c5d6ea-cb22-4cf7-a7a1-c8d5a0e2fc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'like-a-beast' and (text() = 'Like A Beast' or . = 'Like A Beast')]</value>
      <webElementGuid>fe4aa03c-00ef-40b3-bdd5-d8d0702d77fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
