<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Polyhedral Muscular Stance</name>
   <tag></tag>
   <elementGuidId>10a22182-8a66-43d7-ae90-98bbc7023cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#polyhedral-muscular-stance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='polyhedral-muscular-stance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Polyhedral Muscular Stance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4656f887-620d-461f-b997-da467934a9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>polyhedral-muscular-stance</value>
      <webElementGuid>ddd8f93b-e5a9-45fd-8884-59668d49b105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-text</value>
      <webElementGuid>1ea5bc1a-6c96-443b-85e1-8ae6b4ee2d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Polyhedral Muscular Stance</value>
      <webElementGuid>1541ad9a-fdbc-4564-9e16-efd2d7025c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;polyhedral-muscular-stance&quot;)</value>
      <webElementGuid>735449fc-f6c9-49e4-8d6a-87de51af3067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='polyhedral-muscular-stance']</value>
      <webElementGuid>54fa462a-eb5a-4ad4-afaa-3856c6cd363b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='design-block']/div/div[2]/div/h2</value>
      <webElementGuid>ecc2b972-6f71-4d97-a835-fe9bd4e6e3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Modal Dialog'])[2]/following::h2[1]</value>
      <webElementGuid>8397eaea-31ba-427a-86db-996a867c2c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[2]/following::h2[1]</value>
      <webElementGuid>9f39fcfa-631e-436a-9a35-3e68e52ad5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polyhedral Muscular Stance'])[2]/preceding::h2[1]</value>
      <webElementGuid>af39e640-2722-4a4f-9ea5-1b67ca568796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Futuristic Front Fascia'])[1]/preceding::h2[1]</value>
      <webElementGuid>94c832e6-9c3d-4a23-9563-597b6f5ebb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Polyhedral Muscular Stance']/parent::*</value>
      <webElementGuid>2ccbdc6d-142c-41e0-be80-3f5309892136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>7fd14fbf-0a03-46e7-91f9-581023506366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'polyhedral-muscular-stance' and (text() = 'Polyhedral Muscular Stance' or . = 'Polyhedral Muscular Stance')]</value>
      <webElementGuid>c4a821c5-9a4c-467c-ae96-562d47640bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
