<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Suzuki Connect</name>
   <tag></tag>
   <elementGuidId>d0d67ce9-0ccc-4ec9-83d6-5fb2c69f3243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suzuki-connect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='suzuki-connect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Suzuki Connect&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>febcc1c1-a60e-4ef8-b207-35905e7371a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suzuki-connect</value>
      <webElementGuid>a151ffad-8890-48db-a914-e1d613881f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yy8-highlight-tabs__title</value>
      <webElementGuid>828b6026-40fa-431d-8390-5e5998e02999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suzuki Connect</value>
      <webElementGuid>73e5d3db-9623-45e8-b8a0-2dfa11d2be6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suzuki-connect&quot;)</value>
      <webElementGuid>7d9e37b1-35c4-4780-8256-c335e5009a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='suzuki-connect']</value>
      <webElementGuid>f60c62b2-1a9d-4d96-a822-7525a04b9f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='connect-block']/div/div/h2</value>
      <webElementGuid>5c35a177-42c0-4869-9759-63b8d8f709cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Gen'])[1]/following::h2[1]</value>
      <webElementGuid>c05fc476-8111-4d99-9c09-f9a3772505ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety Tech'])[2]/following::h2[1]</value>
      <webElementGuid>c2914509-341c-441f-9b12-96fffaa7aa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Watch Connectivity'])[1]/preceding::h2[1]</value>
      <webElementGuid>681dddff-9c0a-4c87-bca1-b1c0b468f333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Status &amp; Alerts'])[1]/preceding::h2[1]</value>
      <webElementGuid>005b7e45-b581-49ab-8b53-cd631729e015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h2</value>
      <webElementGuid>0d74de68-2643-49c5-adeb-8956510040ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'suzuki-connect' and (text() = 'Suzuki Connect' or . = 'Suzuki Connect')]</value>
      <webElementGuid>32af226b-a4e4-4f55-b757-6aba4a308141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
