<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Download Brochure</name>
   <tag></tag>
   <elementGuidId>9c2a1a48-be3b-45df-852a-96c3ae26c753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#download-brochure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='download-brochure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Download Brochure&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>fb3e5ca9-6353-428e-a903-c3baf1131fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>download-brochure</value>
      <webElementGuid>fede309e-b186-4e07-ae6b-5c29bc0652c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>teaser__title-text</value>
      <webElementGuid>72efbe99-b99e-4a8b-9cfb-8996e424956b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Brochure</value>
      <webElementGuid>d15a6bac-f829-4604-90af-c65279c6509d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;download-brochure&quot;)</value>
      <webElementGuid>d304ab3d-56a9-4282-8ba0-bde5d1545614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='download-brochure']</value>
      <webElementGuid>821c3f3c-9e23-4c41-aeff-a517a51d78b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dealer-cards']/div/div[2]/div/div/div/div/div[2]/div/div/h3</value>
      <webElementGuid>3d271c5f-a400-45a9-963e-90ee0896df0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service On Wheels'])[2]/following::h3[1]</value>
      <webElementGuid>17f1ff9b-0edc-44cc-b312-9a6c9bff99c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e for me App'])[2]/following::h3[2]</value>
      <webElementGuid>e911435b-7d40-46e2-b586-2a9032d3f1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Brochure'])[2]/preceding::h3[1]</value>
      <webElementGuid>b4b6cd34-b738-40a3-b187-3805985ed65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register your interest'])[2]/preceding::h3[1]</value>
      <webElementGuid>092a69cc-1146-4fd8-8151-15f668824cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Brochure']/parent::*</value>
      <webElementGuid>49be0a14-7af6-466e-bc48-2e189fac415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h3</value>
      <webElementGuid>aca63e27-89a5-49f7-b8c2-cb72c75f2c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'download-brochure' and (text() = 'Download Brochure' or . = 'Download Brochure')]</value>
      <webElementGuid>f809a755-24da-49bc-803c-b207746b222b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
